FROM mediawiki:latest

RUN git clone --depth 1 https://gerrit.wikimedia.org/r/mediawiki/extensions/TemplateStyles /var/www/html/extensions/TemplateStyles

RUN git clone --depth 1 https://gerrit.wikimedia.org/r/mediawiki/extensions/JsonConfig /var/www/html/extensions/JsonConfig